<%@ Page Title="" Language="C#" MasterPageFile="~/EasternCuisine/EasternStaff.Master" AutoEventWireup="true" CodeBehind="EasternRequestManagement.aspx.cs" Inherits="OnlineVirtualCookingSchool.EasternCuisine.EasternRequestManagement" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <section>
        <div class="container" style="align-content:center; text-align: center;">
        <h1>EASTERN CUISINE</h1>
        <hr />
        <br />
        <h3>STUDENT ENROLLMENT REQUESTS</h3>
        <br />
        <hr />
        <asp:Button ID="Button1" runat="server" Text="View Requests" BackColor="RoyalBlue" ForeColor="White" Height="40px" Width="200px" OnClick="Button1_Click"/>
        <br />
        <br />
        <asp:GridView ID="GdRequests" runat="server" Width="1179px" DataKeyNames="Stid" AutoGenerateDeleteButton="true" OnRowDeleting="GdRequests_RowDeleting" ></asp:GridView>
            <br />
            <asp:Label ID="Label4" runat="server"  ForeColor="Red"></asp:Label>
            <br />
            <br />
            <hr />
            <br />
            <br />
            <h3>COURSE ENROLLMENT</h3>
            <br />
            <br />
            <table border="1" align="center">
                <tr>
                    <td>
                        <asp:Label ID="Label1" runat="server" Text="Student Email"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                    <br />
                    </td>
                    <td>
                        <asp:Label ID="Label2" runat="server" Text="Level"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:DropDownList ID="DDLevel" runat="server"  DataTextField="lname" DataValueField="lname" OnSelectedIndexChanged="DDLevel_SelectedIndexChanged" DataSourceID="SqlDataSource1">
                            <asp:ListItem Value="0" Text="--select level--"></asp:ListItem>
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:OVCSConnectionString11 %>" SelectCommand="SELECT [lname] FROM [Levels]"></asp:SqlDataSource>
                        <br />
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Button ID="Button2" runat="server" Text="Enroll Student" Width="170px" BackColor="RoyalBlue" ForeColor="White" OnClick="Button2_Click"/>
                        <br />
                    </td>
                    <td>
                        <asp:Label ID="Label3" runat="server" ForeColor="Red"></asp:Label>
                        <br />
                    </td>
                </tr>
            </table>
            <br />
            <br />
            <br />

            <h3>ENROLLED STUDENTS</h3>
        <br />
        <hr />
        <asp:Button ID="Button3" runat="server" Text="View Enrolled Students" BackColor="RoyalBlue" ForeColor="White" Height="40px" Width="200px" OnClick="Button3_Click"/>
        <br />
        <br />
        <asp:GridView ID="GdEnrollments" runat="server" Width="1179px" DataKeyNames="Eeid" AutoGenerateDeleteButton="true" OnRowDeleting="GdEnrollments_RowDeleting" ></asp:GridView>
            <br />
            <asp:Label ID="Label5" runat="server"  ForeColor="Red"></asp:Label>
            <br />
            <br />
            <hr />
            <br />
            <br />

        </div>

    </section>
</asp:Content>
